### ISSUE TITLE
NoClassDefFoundError when using GlowAPI.Color.Green

### ISSUE THREAD

**Issue by Sebastian-Sole** [InventivetalentDev/GlowAPI#101]
**Describe the bug**
When using GlowAPI.setGlowing(Entity entity, GlowAPI.Color color, Collection<Player> receivers), a NoClassDefFoundError is thrown, stating it "Could not initialize class org.inventivetalent.glow.GlowAPI$Color". 

**To Reproduce**
1. Update server to 1.18
2. Join server

**Expected behavior**
Expected player to be set to glowing with the color

**Screenshots**

<img width="711" alt="Screen Shot 2021-12-04 at 22 08 28" src="https://user-images.githubusercontent.com/71325332/144724627-f5e4d36f-d1be-4b07-9177-c54bc66c9aaf.png">

**Additional context**
First time trying to use this API. It imports it and runs the command, but it seems like it can't run GlowAPI.Color.Green.

**Comment by thiagogebrimm** [comment]
Same problem

**Comment by Sebastian-Sole** [comment]
> Same problem

I think it's because I am using 1.18, and this plugin does not support it. It seems like this project is inactive and that the developer won't update it for a while, if ever. Best bet is to find another plugin, (which I have tried and none actually work), or develop one yourself

**Comment by InventivetalentDev** [comment]
PRs are welcome to fix the issue :)

**Comment by Sebastian-Sole** [comment]
> PRs are welcome to fix the issue :)

Thanks for the reply. I don't know what the issue is, I have tried fixing it, but I think that it is because GlowAPI isn't supported on 1.18. I don't know how to fix this problem. I would love to help fix this issue, is there any way that I can contact you? I have followed you on twitter and joined your discord, but I can't figure out how to reach out. Thanks

**Comment by OskarZyg** [comment]
Why don't we just use adventure's existing [NamedTextColor](https://jd.adventure.kyori.net/api/4.9.3/net/kyori/adventure/text/format/NamedTextColor.html)? It's already used in parts of paper that interfere with glow...

**Comment by Sebastian-Sole** [comment]
> Why don't we just use adventure's existing [NamedTextColor](https://jd.adventure.kyori.net/api/4.9.3/net/kyori/adventure/text/format/NamedTextColor.html)? It's already used in parts of paper that interfere with glow...

Just tried, it still doesn't work. I'm still getting an error for NoClassDefFoundError, and if I move the Color into a separate Enum file, it throws the same error but for this:

<img width="1084" alt="Screen Shot 2021-12-21 at 17 52 51" src="https://user-images.githubusercontent.com/71325332/146968262-ae4311e7-bd5a-439f-a5df-a6edf3d8f0bf.png">

I think that the easiest solution is for @InventivetalentDev to update the API to work on 1.18. @InventivetalentDev, if you don't want to do this in the future, I'd be more than happy to contribute to the repository in the future to keep it updated when newer versions of minecraft come out, I just don't know how to do it for this update.

**Comment by HexedHero** [comment]
Most issues are fixed by #100 #102 & #103 then there is just a mapping change for getting the entity on 1.18 here https://github.com/InventivetalentDev/GlowAPI/blob/master/src/org/inventivetalent/glow/GlowAPI.java#L633-L687

**Comment by kiloRs** [comment]
Any update on a fix?

**Comment by InventivetalentDev** [comment]
https://github.com/InventivetalentDev/GlowAPI/releases/tag/1.5.2-SNAPSHOT

**Comment by Sebastian-Sole** [comment]
> https://github.com/InventivetalentDev/GlowAPI/releases/tag/1.5.2-SNAPSHOT

I am on the train right now, but will test this out asap. Thank you for the update <3

**Comment by Sebastian-Sole** [comment]
When adding the dependency, I get this error message:
<img width="1170" alt="Screen Shot 2022-01-02 at 18 53 05" src="https://user-images.githubusercontent.com/71325332/147884814-f10e71af-0073-4433-bf90-fbbac093f260.png">
<img width="421" alt="Screen Shot 2022-01-02 at 18 53 13" src="https://user-images.githubusercontent.com/71325332/147884817-1e2dc282-3c69-4deb-8133-eada7043303b.png">

Anyone have any suggestions or updates?

**Comment by Sebastian-Sole** [comment]
Any update?

**Comment by InventivetalentDev** [comment]
@Sebastian-Sole uploaded it back to repo.inventivetalent.org, jitpack keeps timing out for some reason 🤷

**Comment by Placeblock** [comment]
Same problem here, version 1.5.1 doesn't work, but gradle doesn't find 1.5.2 or 1.5.3...
In jitpack it only shows the build.log for version 1.5.2 and 1.5.3

**Comment by Placeblock** [comment]
Just tested it with the new version 1.5.4-SNAPSHOT
Still not working, (Paper 1.18.2)

**Comment by Sebastian-Sole** [comment]
Any update on this?

**Comment by InventivetalentDev** [comment]
@Sebastian-Sole like I said, I added the updated versions to [repo.inventivetalent.org](https://repo.inventivetalent.org/#browse/browse:maven-snapshots:org%2Finventivetalent%2Fglowapi%2F1.5.4-SNAPSHOT%2F1.5.4-20220714.113019-1) not sure what kind of update you're expecting.  
though you might want to try installing GlowAPI as a plugin to your server and depending on it instead of just shading, iirc there were some changes in 1.17+ that broke support for that.
